server:
  port: 8888
spring:
  application:
    name: proxy

eureka:
  client:
    serviceUrl:
      defaultZone: http://hmily:111@localhost:8761/eureka/


#zuul:
#    routes:
#        userApi:
#            path: /home/**
#            stripPrefix: false
#            serviceId: user
#
#      http://localhost:8081/home
#      http://localhost:8888/user/home
#      http://localhost:8888/home