server:
  port: 8761
spring:
  application:
    name: registry

security:
  basic:
    enabled: true
  user:
    name: hmily
    password: 111
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://hmily:111@localhost:${server.port}/eureka/