server:
  port: 8081
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/imooc_user
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://hmily:111@localhost:8761/eureka/